"""Change Transmission to int@

Revision ID: 16a7bea996b4
Revises: 93a568e08a62
Create Date: 2022-05-19 23:11:22.661251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a7bea996b4'
down_revision = '93a568e08a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto', schema=None) as batch_op:
        batch_op.drop_column('img_url_3')
        batch_op.drop_column('img_url_2')
        batch_op.drop_column('img_url_1')
        batch_op.drop_column('img_url_4')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_url_4', sa.TEXT(length=128), nullable=True))
        batch_op.add_column(sa.Column('img_url_1', sa.TEXT(length=128), nullable=True))
        batch_op.add_column(sa.Column('img_url_2', sa.TEXT(length=128), nullable=True))
        batch_op.add_column(sa.Column('img_url_3', sa.TEXT(length=128), nullable=True))

    # ### end Alembic commands ###
